version: '3'

services:
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - ./dbdata:/data/db:cached

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: kops_api
    container_name: kops_api
    depends_on:
      - db
    environment:
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_URL
      - DATABASE_DB
      - NODE_ENV
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app:cached
      - /home/node/app/node_modules
