version: '3'

services:
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: kops_api
    container_name: kops_api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_HOSTNAME
      - DATABASE_PORT
      - DATABASE_DB
    ports:
      - "80:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
